```{r}
library(corrplot)
#setwd("/home/gbakie/neu/stat-sp16/project/Online_News_Popularity")
setwd("/Users/Darshan/Documents/Online_News_Popularity")

library(caret)
source("DataPreprocess.R")

set.seed(464)

setwd("/Users/Darshan/Documents/CS 7280 Stats/Project/Data/")
#setwd("/home/gbakie/neu/stat-sp16/project/data")

news <- read.csv("Train.csv", header = TRUE)

news <- data_cleaning(news)

url <- news$url
news$url <- NULL

categorical_var <- c("data_channel_is_lifestyle", 
                     "data_channel_is_entertainment", "data_channel_is_bus", 
                     "data_channel_is_world", "data_channel_is_socmed", 
                     "data_channel_is_tech", "weekday_is_monday", "weekday_is_tuesday", 
                     "weekday_is_wednesday", "weekday_is_thursday", "weekday_is_friday", 
                     "weekday_is_saturday", "weekday_is_sunday")

#news_with_cat <- subset(news, select = categorical_var)

news <- subset(news, select = setdiff(names(news),categorical_var))
#news <- cook_outliers_removal(news)

news_train_matrix <- as.matrix(news)
news_train_cor <- cor(news_train_matrix)

corrplot(news_train_cor, type  = "lower", diag = FALSE, tl.cex=0.75)

news_train <- correlation_cleaning(news_train)


news_train_matrix <- as.matrix(news_train)
news_train_cor <- cor(news_train_matrix)

corrplot(news_train_cor, type  = "lower", diag = FALSE, tl.cex=0.7)

```

```{r}

round(cor(news_train[,c(3:4)]), digits=3)
news_train$n_non_stop_unique_tokens <- NULL

round(cor(news_train[,c(17:23)]), digits=3)

```

```{r}
round(cor(news_train[,c(19:21)]), digits=3)
```

```{r}
#news_train$kw_min_min <- NULL
```

```{r}
# self_reference_avg_sharess has 0.829 colinearity with self_reference_min_sharess and 0.848 colinearity with self_reference_max_sharess
round(cor(news_train[,c(26:28)]), digits=3)
news_train$self_reference_avg_sharess <- NULL
# Option 


```

```{r}
#Correlation between rate_positive_words and rate_negative_words is -0.997
round(cor(news_train[,c(46:48)]), digits=3)

news_train$rate_negative_words <- NULL
```

