```{r}

#setwd("/home/gbakie/neu/stat-sp16/project/Online_News_Popularity")
setwd("/Users/Darshan/Documents/Online_News_Popularity")

library(caret)
library(ggplot2)
library(grid)
library(gridExtra)
source("DataPreprocess.R")

set.seed(464)

setwd("/Users/Darshan/Documents/CS 7280 Stats/Project/Data/")
#setwd("/home/gbakie/neu/stat-sp16/project/data")

news <- read.csv("Train.csv", header = TRUE)

news <- data_cleaning(news)
news <- correlation_cleaning(news)

# Can not apply transformation on weighted regression

# return_obj <- target_transformation(news)
# news <- return_obj$news
# lamda <- return_obj$lambda

obj <- normalization(news)
news <- obj$news

news <- cat_encoding(news)

url <- news$url
news$url <- NULL

categorical_var <- c("data_channel_is_lifestyle", 
                     "data_channel_is_entertainment", "data_channel_is_bus", 
                     "data_channel_is_world", "data_channel_is_socmed", 
                     "data_channel_is_tech", "weekday_is_monday", "weekday_is_tuesday", 
                     "weekday_is_wednesday", "weekday_is_thursday", "weekday_is_friday", 
                     "weekday_is_saturday", "weekday_is_sunday")

news_with_cat <- subset(news, select = categorical_var)
news <- subset(news, select = setdiff(names(news),categorical_var))

news_wo_outlier <- cook_outliers_removal(news)

model <- lm(shares ~ ., data=news)

news$res <- abs(model$residuals)
news$pre <- predict(model, data=news)

model <- lm(shares ~ ., data=news_wo_outlier)

news_wo_outlier$res <- abs(model$residuals)
news_wo_outlier$pre <- predict(model, data=news_wo_outlier)


# df <- data.frame(x = news$pre, y = news$res,
#   d = densCols(news$pre, news$res , colramp = colorRampPalette(rev(rainbow(10, end = 4/6)))))
# p <- ggplot(df) +
#     geom_point(aes(x, y, col = d), size = 1) +
#     scale_color_identity() +
#     theme_bw()
# print(p)

#ggplot(aes(x=pre,y=res) ,data=news)  +  geom_point() + scale_colour_gradient(limits=c(1, 5), #low="red")

p1 <- ggplot(aes(x=pre,y=res) ,data=news)  +  geom_point() + xlab("Predicted Number of Shares (With Outliers)") + ylab("abs(Residual)") + stat_binhex(bins = 75)  + geom_smooth(color = "red") + theme(axis.title=element_text(size=9,face="bold"))

p2 <- ggplot(aes(x=pre,y=res) ,data=news_wo_outlier)  +  geom_point() + xlab("Predicted Number of Shares (Without Outliers)") + ylab("abs(Residual)") + stat_binhex(bins = 75)  + geom_smooth(color = "red") + theme(axis.title=element_text(size=9,face="bold"))

grid.arrange(p1, p2, ncol = 2, top = "Residual vs Predicted value of Shares")
#qplot(pre, res, data = news, geom="hex",binwidth = c(0.1, 0.1))

```

Residual plot analyses for finalized stepwise regression model to test whether linear
model is an appropreate model for the given dataset.
```{r}

#setwd("/home/gbakie/neu/stat-sp16/project/Online_News_Popularity")
setwd("/Users/Darshan/Documents/Online_News_Popularity")

library(caret)
library(ggplot2)
library(grid)
library(gridExtra)
source("DataPreprocess.R")

set.seed(464)

setwd("/Users/Darshan/Documents/CS 7280 Stats/Project/Data/")
#setwd("/home/gbakie/neu/stat-sp16/project/data")

news <- read.csv("Train.csv", header = TRUE)

news <- data_cleaning(news)
news <- correlation_cleaning(news)

return_obj <- target_transformation(news)
news <- return_obj$news
lamda <- return_obj$lambda

obj <- normalization(news)
news <- obj$news

news <- cat_encoding(news)

url <- news$url
news$url <- NULL

categorical_var <- c("data_channel_is_lifestyle", 
                     "data_channel_is_entertainment", "data_channel_is_bus", 
                     "data_channel_is_world", "data_channel_is_socmed", 
                     "data_channel_is_tech", "weekday_is_monday", "weekday_is_tuesday", 
                     "weekday_is_wednesday", "weekday_is_thursday", "weekday_is_friday", 
                     "weekday_is_saturday", "weekday_is_sunday")

news_with_cat <- subset(news, select = categorical_var)
news <- subset(news, select = setdiff(names(news),categorical_var))

#news_wo_outlier <- cook_outliers_removal(news)

model <- lm(shares ~ data_channel +
             cat_dow +
             i_kw_max_avg_avg +
             self_reference_avg_sharess +
             i_kw_avg_max_max +
             num_hrefs +
             global_subjectivity +
             LDA_00 +
             LDA_01 +
             LDA_02 +
             num_self_hrefs +
             i_n_unique_tokens_content +
             i_title_sub_sent_polarity +
             abs_title_subjectivity +
             n_tokens_title +
             min_positive_polarity +
             num_imgs +
             average_token_length +
             title_sentiment_polarity + 
             i_min_avg_negative_pol, data=news)

news$res <- abs(model$residuals)
news$pre <- predict(model, data=news)
y <- quantile(news$res, c(0.25, 0.75))
x <- qnorm(c(0.25, 0.75))
slope <- diff(y)/diff(x)
int <- y[1L] - slope * x[1L]
p1 <- ggplot(news, aes(sample=res)) + stat_qq() + geom_abline(slope = slope, intercept = int)  + ylab("Stepwise Regression model residuals (With Outlier)") + theme(axis.title=element_text(size=9,face="bold"))

news_wo_outlier <- cook_outliers_removal(news)

model <- lm(shares ~ num_hrefs +
             num_self_hrefs +
             num_imgs +
             self_reference_avg_sharess +
             LDA_00 +
             LDA_02 +
             global_subjectivity +
             global_rate_positive_words +
             global_rate_negative_words +
             min_positive_polarity +
             max_negative_polarity +
             title_sentiment_polarity +
             abs_title_subjectivity +
             i_n_unique_tokens_content +
             i_rate_pos_gsent_polarity +
             i_kw_max_avg_avg +
             i_kw_avg_max_max +
             cat_dow +
             data_channel + 
             i_title_sub_sent_polarity, data=news_wo_outlier)

news_wo_outlier$res <- abs(model$residuals)
news_wo_outlier$pre <- predict(model, data=news)

y <- quantile(news_wo_outlier$res, c(0.25, 0.75))
x <- qnorm(c(0.25, 0.75))
slope <- diff(y)/diff(x)
int <- y[1L] - slope * x[1L]

p2 <- ggplot(news_wo_outlier, aes(sample=res)) + stat_qq() +geom_abline(slope = slope, intercept = int) + ylab("Stepwise Regression model residuals (Without Outlier)") + theme(axis.title=element_text(size=9,face="bold"))
grid.arrange(p1, p2, ncol = 2, top = "Residual QQ Plots")
```